# Numpy libaray

In [1]:
# first import libaray
import numpy as np

In [3]:
# check version
np.__version__

'1.19.2'

In [6]:
# make first array
arr = np.array([[1,2,3,4,5]])

# printing array
arr

array([[1, 2, 3, 4, 5]])

In [7]:
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
type(arr)

numpy.ndarray

## Dimensions in Arrays


In [8]:
# create 0-D array
arr = np.array(46)

arr

array(46)

In [9]:
# create 1-D array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [10]:
# How to Knows Dimensions of array?
# use ndim attribute
arr.ndim

1

In [11]:
# create 2-D array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# check d of arr
arr.ndim

2

### Array Indexing | Access Array Elements

In [13]:
# use [index of element will needed return]
# 1 - create 1-d array
arr = np.array([1,2,3,4,5])

# return element value equal 3 
# note index we start with zero 
# so, first element value = 1 => index = 0
arr[2] # 2 index equal thrid elements in array

3

In [14]:
# Access element from array 2-D
# create array 2-D 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Access element value = 2 from first row 
# Access element value = 8 from second row
# now we use [index of row, index element in row]
print(arr[0,1]) # 0 => first row, 1 index element in first row will return element value = 2
print(arr[1,2]) # 1 => second row, 2 thrid element in second row, we will return element = 8

2
8


In [15]:
# return last element by use negtive index
arr[-1]

array([ 6,  7,  8,  9, 10])

### Slice array [start:end:step].

In [16]:
# note : end index not include with return element

In [17]:
# create array with 1-D
arr = np.array([1,2,3,4,5])
# example
# slice start from index equal = 1 , and end last element => 5, Ay return [2,3,4,5]
print(arr[1:])

[2 3 4 5]


In [18]:
arr[1:-1]

array([2, 3, 4])

In [21]:
# Slice from array with 2-D
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# example
# Slice from array first and return last 3 element
arr[0,2:] # 0 fisrt row , 2: element will return from first row

array([3, 4, 5])

In [26]:
# how return first two element from all row 
arr[:,0:2] # (:) we pointer all row , 0:2 return first two element from all row

array([[1, 2],
       [6, 7]])

### array Datatypes

In [30]:
# how knows data type of array?  use dtype attribute
arr.dtype

dtype('int32')

In [31]:
# what data type can make array?

integer, string , bool, float, complex, datetime and soon

In [33]:
# How to definte type of array
arr = np.array([1,2,3], dtype='S') # S=> string
# print array
print(arr)
# print type of array
print(arr.dtype)

[b'1' b'2' b'3']
|S1


### Array Copy and Views

In [34]:
# Use copy function to copy array => return new array
newarr = arr.copy()

# print new array
newarr

array([b'1', b'2', b'3'], dtype='|S1')

In [39]:
# View()
arr = np.array([1,2,3,4,5])

# make view 
viewarr = arr.view()
# print view array
viewarr

array([1, 2, 3, 4, 5])

In [40]:
# but what about chnage in vewier array
viewarr[0] = 6
# print array 
viewarr

array([6, 2, 3, 4, 5])

In [41]:
# do you change doing in orginal array?
arr

array([6, 2, 3, 4, 5])

In [38]:
# answer is yes
# in copy array not orignal changed with change in cop array

In [43]:
print(arr.copy().base)

None


In [44]:
print(arr.view().base)

[6 2 3 4 5]


### Shape of Arrays

In [45]:
arr.shape

(5,)

In [46]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# return Shape of array
arr.shape

(2, 5)

### ReShape array

In [47]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# Shape of array
arr.shape

(9,)

In [48]:
# we reshape to (3,3) and return new array
arr = arr.reshape(3,3)
# print array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.shape

(3, 3)

### Iterating Arrays


In [50]:
# for example
arr = np.array([1,2,3,4,5])

# we needed print all element
def printArray():
    for item in arr:
        print(item)
printArray()

1
2
3
4
5


In [51]:
# definte function take array and return newarray equal array input plus 3 for all item in element
# we use np.ndenumerate
def addThree(arr):
    return arr + 3

arr = addThree(arr)
arr

array([4, 5, 6, 7, 8])

In [52]:
# anthoer ways
def addThree(arr):
    for index,item in np.ndenumerate(arr):
        arr[index] = item + 3
    return arr
arr = addThree(arr)
arr

array([ 7,  8,  9, 10, 11])

### Array Join

In [3]:
# make arrays to join 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# join array
# to join use concatenate((array_left, array_right) => as tuple)
arr = np.concatenate((arr1,arr2))

# print new array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# join 2-D array by use axis primater equal = 1, Ay join by row , first row with first row , and so on.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1,arr2), axis=1)

# print new arr
arr 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
# Using Stack function other way to join.
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
# make new array with columns equal length element in array , so length to all array ot join must be equal.
# first element with first element , and so on.
arr = np.stack((arr1,arr2), axis=1)

# print new array
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
# hstack() return array with 1-D contains all element in arrays we will joined
arr = np.hstack((arr1,arr2))

# print new array
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### Array Split

In [13]:
# array_split(array, number of element we will split from array)
# return a list contain a number from array equal number of input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

newarr = np.array_split(arr,3)

# print new array
newarr

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [14]:
# check a type of newarr
type(newarr)

list

In [15]:
# to Access array element in list is very easy
newarr[0] # to access first item in list => equal array

array([1, 2, 3, 4])

In [16]:
# to access first element in first item in list
newarr[0][0]

1

### Array Sreach

In [23]:
# Using Where Function np.where(condtaion)

arr = np.array([1,2,3,4,5])

# make search item value = 4 in array
# return atupe contain array with index element in array and dtype of elements.
# if else not found return -1
x = np.where(arr == 4)
print(x)

(array([3], dtype=int64),)


In [20]:
arr[x]

array([4])

In [25]:
# return index all element with mod 2 equal ==0, Ay index of even number in array

arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 0)
x

(array([1, 3, 5, 7], dtype=int64),)

In [27]:
# Search by Use searchsorted(take array, number to Searching about to)
# return index number searching it.
# Search number 6 and return index 
# we will return index number of 6, he equal: 5
np.searchsorted(arr,6)

5

In [30]:
# can you search more one element 
# take a list number to searching not number
# we will return array contains index number of searching
np.searchsorted(arr, [2,5,7])

array([1, 4, 6], dtype=int64)

In [29]:
# check type 
type(np.searchsorted(arr, [2,5,7]))

numpy.ndarray

### Array Sort

In [33]:
# Use np.sort() to Sorting array
arr = np.array([0,3,4,1,2,5])

# sort array and return new array
arr = np.sort(arr)

# print  array override
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
# can you sort String 
arr = np.array(['banana', 'cherry', 'apple'])
np.sort(arr)

array(['apple', 'banana', 'cherry'], dtype='<U6')

### Array Filtering

In [35]:
# How Filtering array
arr = np.array([1,2,3,4,5,6])

# return even array 
# make a condtion
filter_con = arr % 2 == 0

# resluit in new array
newarr = arr[filter_con]

# print new array
newarr

array([2, 4, 6])

In [36]:
# print filter condtions
filter_con

array([False,  True, False,  True, False,  True])

In [37]:
# by way not direct from array
# create array
arr = np.array([1,2,3,4,5,6,7,8])
def filterEvenNumber(arr):
    # create empty array to add resluit 
    newarr = []

    # looping in all element in array 
    for item in arr:
    #     if condtion
        if item % 2 == 0:
    #         add element in empty array
            newarr.append(item)
    return newarr

filterEvenNumber(arr)

[2, 4, 6, 8]