In [1]:
# Random number in Numby

In [2]:
# importing libaray
import numpy as np 

* Generate Random Number
* NumPy offers the random module to work with random numbers.

In [4]:
# Generate a random integer from 0 to 100:
# return random number from zero  to 100 (but not included).
randn = np.random.randint(100)

# print random number
randn

6

In [7]:
# Generate a random float from zero to 100.
# float number must be from 0 to 1 (not input pramter in function rand)
# return float random number from zero to 100(but not included).
randf = np.random.rand()

randf

0.1653950623532675

### - Generate Random Array


In [8]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
# return array contain number of size random number from zero to "number input"
# randint(number of end to return random number, size = number => number of size array)
# example return random array from zero to 100(but not included ), and size of array = 5.
from numpy import random as rn
arr = rn.randint(100, size=5)

# print random array
arr

array([ 0, 95, 39, 61, 74])

In [11]:
# can you return random array but 2-D not 1-D => size must atuple taken two number (row,columns)
# for example 
arr = rn.randint(100, size = (5,3))

# print array
arr

array([[62, 17, 15],
       [17, 40, 33],
       [48, 12, 73],
       [70, 58, 24],
       [62, 61,  7]])

In [12]:
# random float array 1-d
arr = rn.rand(5)
# print array
arr

array([0.29202256, 0.03971283, 0.32609041, 0.19112982, 0.14920086])

### - Generate Random Number From Array


In [13]:
# by using choice function taken a list of number to return random number from the list input
x = rn.choice([1,5,6,9,8,7])

# print random number
x

1

In [14]:
# can return array from the list 
arr = rn.choice([1,2,3,4,5,6,7,8,9], size = 4)

# print arr
arr

array([1, 9, 8, 3])

In [17]:
# Randomly shuffle elements of following array:
# Using Suffle(array to shuffle it)
# The shuffle() method makes changes to the original array.
arr = rn.randint(100, size=5)

print(arr)
rn.shuffle(arr)

print(arr)

[15 91  9 25 45]
[ 9 91 25 45 15]


In [19]:
# Generating Permutation of Arrays
# return new arrayrandom from array 
# changes not makes in original array.
# create array 
arr = np.array([1,2,3,4,5])

# create permutation
re_arr = rn.permutation(arr)

# print re_array
re_arr

array([1, 2, 5, 4, 3])

### * Normal Distribution
